on:
  pull_request:
    branches: '*'
  issue_comment:
    types: [created]

name: Render README

jobs:
  check-not-fork:
    runs-on: macOS-latest
    steps:
      - uses: actions/github-script@v5
        if: github.event.pull_request.head.repo.fork == true
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.number,
              owner: context.repository.owner.login,
              repo: context.repository.name,
              body: 'This PR comes from a fork. README should be rendered manually using `/render` command in a comment.'
            })
            core.setFailed('PR is a fork - render manually')
  render:
    needs: check-not-fork
    name: Render README
    runs-on: macOS-latest
    # Don't run on fork
    if: github.event.pull_request.head.repo.fork == false || startsWith(github.event.comment.body, '/render')
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install packages
        run: |
          install.packages(c("rmarkdown", "magick"))
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Configure Git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Commit results
        run: |
          git add README.md thumbs && git commit -m 'Re-build README.Rmd' || echo "No changes to commit"
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
